<h1> Palmer Penguin Data Analytics </h1>
<hr>
<h3> Berches, Charles Andrei </h3>
<h4> BSIT-3A </h4>

In [1]:
import numpy as np
import pandas as pd
import os
import warnings
warnings.filterwarnings('ignore')

<p>Importing dataset to Jupyter notebook</p>
<p>Converting dataset to dataframe</p>
<ul><b>Requriements</b>
    <li>Name of the dataframe</li>
    <li>Source</li>
</ul>

<h4> Descriptive Analytics </h4>

In [2]:
penguins = pd.read_csv('datasets\\penguins.csv')

In [3]:
penguins

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0       Adelie  Torgersen            39.1           18.7              181.0   
1       Adelie  Torgersen            39.5           17.4              186.0   
2       Adelie  Torgersen            40.3           18.0              195.0   
3       Adelie  Torgersen             NaN            NaN                NaN   
4       Adelie  Torgersen            36.7           19.3              193.0   
..         ...        ...             ...            ...                ...   
339  Chinstrap      Dream            55.8           19.8              207.0   
340  Chinstrap      Dream            43.5           18.1              202.0   
341  Chinstrap      Dream            49.6           18.2              193.0   
342  Chinstrap      Dream            50.8           19.0              210.0   
343  Chinstrap      Dream            50.2           18.7              198.0   

     body_mass_g     sex  year  
0         3750.0    male  2007  
1         3800.0  female  2007  
2         3250.0  female  2007  
3            NaN     NaN  2007  
4         3450.0  female  2007  
..           ...     ...   ...  
339       4000.0    male  2009  
340       3400.0  female  2009  
341       3775.0    male  2009  
342       4100.0    male  2009  
343       3775.0  female  2009  

[344 rows x 8 columns]

In [4]:
print(os.getcwd())

C:\Users\LAB5-StudentPC07\Desktop\ELEC03-3A


In [5]:
penguins.describe()

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
count      342.000000     342.000000         342.000000   342.000000   
mean        43.921930      17.151170         200.915205  4201.754386   
std          5.459584       1.974793          14.061714   801.954536   
min         32.100000      13.100000         172.000000  2700.000000   
25%         39.225000      15.600000         190.000000  3550.000000   
50%         44.450000      17.300000         197.000000  4050.000000   
75%         48.500000      18.700000         213.000000  4750.000000   
max         59.600000      21.500000         231.000000  6300.000000   

              year  
count   344.000000  
mean   2008.029070  
std       0.818356  
min    2007.000000  
25%    2007.000000  
50%    2008.000000  
75%    2009.000000  
max    2009.000000

In [6]:
penguins.describe().T

count         mean         std     min       25%      50%  \
bill_length_mm     342.0    43.921930    5.459584    32.1    39.225    44.45   
bill_depth_mm      342.0    17.151170    1.974793    13.1    15.600    17.30   
flipper_length_mm  342.0   200.915205   14.061714   172.0   190.000   197.00   
body_mass_g        342.0  4201.754386  801.954536  2700.0  3550.000  4050.00   
year               344.0  2008.029070    0.818356  2007.0  2007.000  2008.00   

                      75%     max  
bill_length_mm       48.5    59.6  
bill_depth_mm        18.7    21.5  
flipper_length_mm   213.0   231.0  
body_mass_g        4750.0  6300.0  
year               2009.0  2009.0

<h4> Cleaning the Data Frame </h4>

In [7]:
penguins.isnull()

species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0      False   False           False          False              False   
1      False   False           False          False              False   
2      False   False           False          False              False   
3      False   False            True           True               True   
4      False   False           False          False              False   
..       ...     ...             ...            ...                ...   
339    False   False           False          False              False   
340    False   False           False          False              False   
341    False   False           False          False              False   
342    False   False           False          False              False   
343    False   False           False          False              False   

     body_mass_g    sex   year  
0          False  False  False  
1          False  False  False  
2          False  False  False  
3           True   True  False  
4          False  False  False  
..           ...    ...    ...  
339        False  False  False  
340        False  False  False  
341        False  False  False  
342        False  False  False  
343        False  False  False  

[344 rows x 8 columns]

In [8]:
penguins.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [9]:
penguins.isnull().diff()

species island bill_length_mm bill_depth_mm flipper_length_mm body_mass_g  \
0       NaN    NaN            NaN           NaN               NaN         NaN   
1     False  False          False         False             False       False   
2     False  False          False         False             False       False   
3     False  False           True          True              True        True   
4     False  False           True          True              True        True   
..      ...    ...            ...           ...               ...         ...   
339   False  False          False         False             False       False   
340   False  False          False         False             False       False   
341   False  False          False         False             False       False   
342   False  False          False         False             False       False   
343   False  False          False         False             False       False   

       sex   year  
0      NaN    NaN  
1    False  False  
2    False  False  
3     True  False  
4     True  False  
..     ...    ...  
339  False  False  
340  False  False  
341  False  False  
342  False  False  
343  False  False  

[344 rows x 8 columns]

<h3> Selecting a column </h3>
<h4> Syntax </h4>
data_frame[column_name]

In [10]:
[penguins['island'] == 'Dream']

[0      False
 1      False
 2      False
 3      False
 4      False
        ...  
 339     True
 340     True
 341     True
 342     True
 343     True
 Name: island, Length: 344, dtype: bool]

In [11]:
penguins['species'].unique()

array(['Adelie', 'Gentoo', 'Chinstrap'], dtype=object)

In [12]:
x = penguins[penguins['species'] == 'Gentoo']
y = penguins[penguins['species'] == 'Adelie']
z = penguins[penguins['species'] == 'Chinstrap']

<h3> GENTOO SPECIES </h3>

In [13]:
x

species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
152  Gentoo  Biscoe            46.1           13.2              211.0   
153  Gentoo  Biscoe            50.0           16.3              230.0   
154  Gentoo  Biscoe            48.7           14.1              210.0   
155  Gentoo  Biscoe            50.0           15.2              218.0   
156  Gentoo  Biscoe            47.6           14.5              215.0   
..      ...     ...             ...            ...                ...   
271  Gentoo  Biscoe             NaN            NaN                NaN   
272  Gentoo  Biscoe            46.8           14.3              215.0   
273  Gentoo  Biscoe            50.4           15.7              222.0   
274  Gentoo  Biscoe            45.2           14.8              212.0   
275  Gentoo  Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  year  
152       4500.0  female  2007  
153       5700.0    male  2007  
154       4450.0  female  2007  
155       5700.0    male  2007  
156       5400.0    male  2007  
..           ...     ...   ...  
271          NaN     NaN  2009  
272       4850.0  female  2009  
273       5750.0    male  2009  
274       5200.0  female  2009  
275       5400.0    male  2009  

[124 rows x 8 columns]

<h3> ADELIE SPECIES </h3>

In [14]:
y

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
147  Adelie      Dream            36.6           18.4              184.0   
148  Adelie      Dream            36.0           17.8              195.0   
149  Adelie      Dream            37.8           18.1              193.0   
150  Adelie      Dream            36.0           17.1              187.0   
151  Adelie      Dream            41.5           18.5              201.0   

     body_mass_g     sex  year  
0         3750.0    male  2007  
1         3800.0  female  2007  
2         3250.0  female  2007  
3            NaN     NaN  2007  
4         3450.0  female  2007  
..           ...     ...   ...  
147       3475.0  female  2009  
148       3450.0  female  2009  
149       3750.0    male  2009  
150       3700.0  female  2009  
151       4000.0    male  2009  

[152 rows x 8 columns]

<h3> CHINSTRAP SPECIES </h3>

In [15]:
z

species island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
276  Chinstrap  Dream            46.5           17.9              192.0   
277  Chinstrap  Dream            50.0           19.5              196.0   
278  Chinstrap  Dream            51.3           19.2              193.0   
279  Chinstrap  Dream            45.4           18.7              188.0   
280  Chinstrap  Dream            52.7           19.8              197.0   
..         ...    ...             ...            ...                ...   
339  Chinstrap  Dream            55.8           19.8              207.0   
340  Chinstrap  Dream            43.5           18.1              202.0   
341  Chinstrap  Dream            49.6           18.2              193.0   
342  Chinstrap  Dream            50.8           19.0              210.0   
343  Chinstrap  Dream            50.2           18.7              198.0   

     body_mass_g     sex  year  
276       3500.0  female  2007  
277       3900.0    male  2007  
278       3650.0    male  2007  
279       3525.0  female  2007  
280       3725.0    male  2007  
..           ...     ...   ...  
339       4000.0    male  2009  
340       3400.0  female  2009  
341       3775.0    male  2009  
342       4100.0    male  2009  
343       3775.0  female  2009  

[68 rows x 8 columns]

<h3> HOW MANY CHINSTRAP HAS THE BODY MASS OVER 4000? </h3>

In [16]:
massOfChinstrap = penguins[(penguins['species'] == 'Chinstrap') & (penguins['body_mass_g'] >= 4000)]

In [17]:
massOfChinstrap.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16 entries, 284 to 342
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            16 non-null     object 
 1   island             16 non-null     object 
 2   bill_length_mm     16 non-null     float64
 3   bill_depth_mm      16 non-null     float64
 4   flipper_length_mm  16 non-null     float64
 5   body_mass_g        16 non-null     float64
 6   sex                16 non-null     object 
 7   year               16 non-null     int64  
dtypes: float64(4), int64(1), object(3)
memory usage: 1.1+ KB


In [18]:
sexOfChinstrap = penguins[(penguins['species'] == 'Chinstrap') & (penguins['body_mass_g'] >= 4000) & (penguins['sex'] == 'male')]

In [19]:
sexOfChinstrap.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15 entries, 289 to 342
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            15 non-null     object 
 1   island             15 non-null     object 
 2   bill_length_mm     15 non-null     float64
 3   bill_depth_mm      15 non-null     float64
 4   flipper_length_mm  15 non-null     float64
 5   body_mass_g        15 non-null     float64
 6   sex                15 non-null     object 
 7   year               15 non-null     int64  
dtypes: float64(4), int64(1), object(3)
memory usage: 1.1+ KB


<h3> HOW MANY CHINSTRAP PENGUINS IS MALE? </h3>

In [20]:
penguins[(penguins['species'] == 'Chinstrap') & (penguins['body_mass_g'] >= 4000) & (penguins['sex'] == 'male')].info()

<class 'pandas.core.frame.DataFrame'>
Index: 15 entries, 289 to 342
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            15 non-null     object 
 1   island             15 non-null     object 
 2   bill_length_mm     15 non-null     float64
 3   bill_depth_mm      15 non-null     float64
 4   flipper_length_mm  15 non-null     float64
 5   body_mass_g        15 non-null     float64
 6   sex                15 non-null     object 
 7   year               15 non-null     int64  
dtypes: float64(4), int64(1), object(3)
memory usage: 1.1+ KB


<h3> HOW MANY CHINSTRAP PENGUINS IS FEMALE? </h3>

In [21]:
penguins[(penguins['species'] == 'Chinstrap') & (penguins['body_mass_g'] >= 4000) & (penguins['sex'] == 'female')].info()

<class 'pandas.core.frame.DataFrame'>
Index: 1 entries, 284 to 284
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            1 non-null      object 
 1   island             1 non-null      object 
 2   bill_length_mm     1 non-null      float64
 3   bill_depth_mm      1 non-null      float64
 4   flipper_length_mm  1 non-null      float64
 5   body_mass_g        1 non-null      float64
 6   sex                1 non-null      object 
 7   year               1 non-null      int64  
dtypes: float64(4), int64(1), object(3)
memory usage: 72.0+ bytes


<h3> HOW TO CHANGE THE VALUE AS A NULL? </h3>

In [22]:
penguins['bill_length_mm'] = penguins['bill_length_mm'].fillna(penguins['bill_length_mm'].mean())
penguins['bill_depth_mm'] = penguins['bill_depth_mm'].fillna(penguins['bill_depth_mm'].mean())
penguins['flipper_length_mm'] = penguins['flipper_length_mm'].fillna(penguins['flipper_length_mm'].mean())
penguins['body_mass_g'] = penguins['body_mass_g'].fillna(penguins['body_mass_g'].mean())
penguins['sex'] = penguins['sex'].fillna(penguins['sex'].mode()[0])

In [23]:
penguins.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
dtype: int64

In [24]:
penguins['species'] = penguins['species'].astype('category')
penguins['island'] = penguins['island'].astype('category')
penguins['sex'] = penguins['sex'].astype('category')
penguins['year'] = penguins['year'].astype('category')

In [25]:
penguins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype   
---  ------             --------------  -----   
 0   species            344 non-null    category
 1   island             344 non-null    category
 2   bill_length_mm     344 non-null    float64 
 3   bill_depth_mm      344 non-null    float64 
 4   flipper_length_mm  344 non-null    float64 
 5   body_mass_g        344 non-null    float64 
 6   sex                344 non-null    category
 7   year               344 non-null    category
dtypes: category(4), float64(4)
memory usage: 12.7 KB


<h3> HOW TO CREATE A COLUMN </h3>

In [26]:
penguins['body_mass_kg'] = np.round(penguins['body_mass_g'] / 1000)
penguins

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0       Adelie  Torgersen        39.10000       18.70000         181.000000   
1       Adelie  Torgersen        39.50000       17.40000         186.000000   
2       Adelie  Torgersen        40.30000       18.00000         195.000000   
3       Adelie  Torgersen        43.92193       17.15117         200.915205   
4       Adelie  Torgersen        36.70000       19.30000         193.000000   
..         ...        ...             ...            ...                ...   
339  Chinstrap      Dream        55.80000       19.80000         207.000000   
340  Chinstrap      Dream        43.50000       18.10000         202.000000   
341  Chinstrap      Dream        49.60000       18.20000         193.000000   
342  Chinstrap      Dream        50.80000       19.00000         210.000000   
343  Chinstrap      Dream        50.20000       18.70000         198.000000   

     body_mass_g     sex  year  body_mass_kg  
0    3750.000000    male  2007           4.0  
1    3800.000000  female  2007           4.0  
2    3250.000000  female  2007           3.0  
3    4201.754386    male  2007           4.0  
4    3450.000000  female  2007           3.0  
..           ...     ...   ...           ...  
339  4000.000000    male  2009           4.0  
340  3400.000000  female  2009           3.0  
341  3775.000000    male  2009           4.0  
342  4100.000000    male  2009           4.0  
343  3775.000000  female  2009           4.0  

[344 rows x 9 columns]

<hr>

<h1> EXPLORATORY DATA ANALYTICS (EDA) </h1>

<h3> 1. Which species had the highest count of living penguins on Dream Island recorded in 2007? </h3>

In [27]:
penguins[(penguins['island'] == 'Dream') & (penguins['year'] == 2007)]['species'].value_counts()

species
Chinstrap    26
Adelie       20
Gentoo        0
Name: count, dtype: int64

<h3> #1 INSIGHT </h3>

<h4> Dream Island had more Chinstrap penguins in the 2007 record. </h4>

<hr>

<h3> 2. How many Gentoo species are female and male? </h3>

In [28]:
penguins[penguins['species'] == 'Gentoo']['sex'].value_counts()

sex
male      66
female    58
Name: count, dtype: int64

<h3> #2 INSIGHT </h3>

<h4> The female count of Gentoo penguins is 58, while the male count is 66. </h4>

<hr>

<h3> 3. How many penguins recorded in 2007 have a bill length over 40? </h3>

In [29]:
penguins[(penguins['year'] == 2007) & (penguins['bill_length_mm'] >= 40)].value_counts().sum()

np.int64(75)

<h3> #3 INSIGHT </h3>

<h4> 75 penguins with a bill length over 40 were recorded in 2007. </h4>

<hr>

<h3> 4. What’s the average bill length of male and female Chinstrap penguins? </h3>

In [30]:
average = penguins[penguins['species'] == 'Chinstrap']

In [31]:
np.round(average[average['sex'] == 'male']['bill_length_mm'].mean())

np.float64(51.0)

In [32]:
np.round(average[average['sex'] == 'female']['bill_length_mm'].mean())

np.float64(47.0)

<h3> #4 INSIGHT </h3>

<h4> The average bill length of male Chinstrap penguins is 51.0, while female Chinstrap penguins is 47.0. </h4>

<hr>

<h3> 5. How many female penguins are living in the Dream Island?</h3>

In [33]:
penguins[(penguins['island'] == 'Dream') & (penguins['sex'] == 'female')].value_counts().sum()

np.int64(61)

<h3> #5 INSIGHT </h3>

<h4> There are 61 female penguins living on Dream Island. </h4>

<hr>

<h3> 6. Which island had the most living female penguins recorded in 2009? </h3>

In [34]:
penguins[(penguins['island'] == 'Biscoe') & (penguins['year'] == 2009) & (penguins['sex'] == 'female')].value_counts().sum()

np.int64(28)

In [35]:
penguins[(penguins['island'] == 'Dream') & (penguins['year'] == 2009) & (penguins['sex'] == 'female')].value_counts().sum()

np.int64(22)

In [36]:
penguins[(penguins['island'] == 'Torgersen') & (penguins['year'] == 2009) & (penguins['sex'] == 'female')].value_counts().sum()

np.int64(8)

<h3> #6 INSIGHT </h3>

<h4> Biscoe Island had the most living female penguins recorded in 2009. </h4>

<hr>

<h3> 7. How many penguins per island have a bill length over 40mm but a body mass less than 3800g? </h3>

In [37]:
penguins[(penguins['bill_length_mm'] >= 40) & (penguins['body_mass_g'] <= 3800)]['island'].value_counts()

island
Dream        51
Torgersen     6
Biscoe        4
Name: count, dtype: int64

<h3> #7 INSIGHT </h3>

<h4> Dream Island has 51 penguins with a bill length over 40mm and a body mass less than 3800g, while Torgersen has 6 and Biscoe has 4. </h4>

<hr>

<hr>

<h1> DATA AGGREGATION </h1>

In [38]:
np.round(penguins)

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0       Adelie  Torgersen            39.0           19.0              181.0   
1       Adelie  Torgersen            40.0           17.0              186.0   
2       Adelie  Torgersen            40.0           18.0              195.0   
3       Adelie  Torgersen            44.0           17.0              201.0   
4       Adelie  Torgersen            37.0           19.0              193.0   
..         ...        ...             ...            ...                ...   
339  Chinstrap      Dream            56.0           20.0              207.0   
340  Chinstrap      Dream            44.0           18.0              202.0   
341  Chinstrap      Dream            50.0           18.0              193.0   
342  Chinstrap      Dream            51.0           19.0              210.0   
343  Chinstrap      Dream            50.0           19.0              198.0   

     body_mass_g     sex  year  body_mass_kg  
0         3750.0    male  2007           4.0  
1         3800.0  female  2007           4.0  
2         3250.0  female  2007           3.0  
3         4202.0    male  2007           4.0  
4         3450.0  female  2007           3.0  
..           ...     ...   ...           ...  
339       4000.0    male  2009           4.0  
340       3400.0  female  2009           3.0  
341       3775.0    male  2009           4.0  
342       4100.0    male  2009           4.0  
343       3775.0  female  2009           4.0  

[344 rows x 9 columns]

<h3> How many male and female exist per species? </h3>

In [39]:
penguins.groupby(['sex', 'species']).count()

island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
sex    species                                                               
female Adelie         73              73             73                 73   
       Chinstrap      34              34             34                 34   
       Gentoo         58              58             58                 58   
male   Adelie         79              79             79                 79   
       Chinstrap      34              34             34                 34   
       Gentoo         66              66             66                 66   

                  body_mass_g  year  body_mass_kg  
sex    species                                     
female Adelie              73    73            73  
       Chinstrap           34    34            34  
       Gentoo              58    58            58  
male   Adelie              79    79            79  
       Chinstrap           34    34            34  
       Gentoo              66    66            66

<h3> How many female and male penguins are recorded from 2007 to 2009? </h3>

In [40]:
penguins.groupby(['sex', 'species', 'year']).size()

sex     species    year
female  Adelie     2007    22
                   2008    25
                   2009    26
        Chinstrap  2007    13
                   2008     9
                   2009    12
        Gentoo     2007    16
                   2008    22
                   2009    20
male    Adelie     2007    28
                   2008    25
                   2009    26
        Chinstrap  2007    13
                   2008     9
                   2009    12
        Gentoo     2007    18
                   2008    24
                   2009    24
dtype: int64

<hr>

<h3> How many female and male penguins per species has the body mass over 4000g? </h3>

In [41]:
penguins[penguins['body_mass_g'] >= 4000].groupby(['sex', 'species']).size()

sex     species  
female  Adelie        0
        Chinstrap     1
        Gentoo       57
male    Adelie       40
        Chinstrap    15
        Gentoo       66
dtype: int64

<hr>

<h3> Average weight per species and per sex of penguin in each Island? </h3>

In [42]:
np.round(penguins.groupby(['sex', 'species', 'island'])['body_mass_g'].mean())

sex     species    island   
female  Adelie     Biscoe       3369.0
                   Dream        3344.0
                   Torgersen    3396.0
        Chinstrap  Biscoe          NaN
                   Dream        3527.0
                   Torgersen       NaN
        Gentoo     Biscoe       4680.0
                   Dream           NaN
                   Torgersen       NaN
male    Adelie     Biscoe       4050.0
                   Dream        4009.0
                   Torgersen    3990.0
        Chinstrap  Biscoe          NaN
                   Dream        3939.0
                   Torgersen       NaN
        Gentoo     Biscoe       5411.0
                   Dream           NaN
                   Torgersen       NaN
Name: body_mass_g, dtype: float64

<hr>

<h1> TESTING CORRELATION </h1>

<h3> Pearson R Correlation </h3>

<hr>
<h4> Used for testing correlation between two <strong> NUMERICAL VALUES </strong> </h4>

<h3> Correlation </h3>

In [43]:
np.round(penguins['body_mass_g'].corr(penguins['bill_length_mm']))

np.float64(1.0)

<h3> No Correlation </h3>

In [44]:
np.round(penguins['body_mass_g'].corr(penguins['bill_depth_mm']))

np.float64(-0.0)

<hr>

<h3> 8. Do males generally weigh more than females accross species? </h3>

<h3> #8 INSIGHT </h3>

<h4>  </h4>

<hr>

<h3> 9. What's the average bill dimensions of male and females penguins per species? </h3>

<h3> #9 INSIGHT </h3>

<h4>  </h4>

<hr>

<h3> 10. What is the distribution of flipper length in every species per sex? </h3>

In [56]:
penguins.groupby(['species', 'sex'])['flipper_length_mm'].mean()

species    sex   
Adelie     female    187.794521
           male      192.087534
Chinstrap  female    191.735294
           male      199.911765
Gentoo     female    212.706897
           male      220.877503
Name: flipper_length_mm, dtype: float64

<h3> #10 INSIGHT </h3>

<h4>  </h4>

<hr>

<h1> Numerical - Categorical Correlation Test </h1>

<h3> Library - SciPy (Scientific Python) </h3>
<hr>
<p> from scipy.stats import f_oneway </p>

In [45]:
from scipy.stats import f_oneway

In [47]:
m , f = f_oneway(penguins[penguins['sex'] == 'male']['body_mass_g'], penguins[penguins['sex'] == 'female']['body_mass_g'])

In [48]:
m

np.float64(68.38476171974526)

In [49]:
f

np.float64(3.0226600487050246e-15)